import type { NextRequest } from "next/server";
import { createAnalyticsContextModule } from "@/analytics-context";

/**
 * @swagger
 * /api/v1/analytics/context/latest:
 *   get:
 *     summary: Get latest unified analytics context
 *     description: Returns the latest available context aggregated from existing module outputs. No recommendations, AI summaries, incidents, or scores are generated by this endpoint.
 *     tags:
 *       - Analytics Context
 *     parameters:
 *       - in: header
 *         name: x-tenant-id
 *         required: true
 *         schema:
 *           type: string
 *       - in: query
 *         name: businessUnitId
 *         schema:
 *           type: string
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *     responses:
 *       200:
 *         description: Latest unified analytics context
 */
export async function GET(request: NextRequest) {
  const { controller } = await createAnalyticsContextModule();
  return controller.getLatestContext(request);
}
